[project]
name = "test01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain[anthropic]>=0.3.27",
    "langgraph>=0.6.3",
    "langsmith>=0.4.10",
]
